final List<String> responses = [
  "Hello! \nWelcome to ChatBot\nHow can I assist you?",
  "Hi!\nWelcome to ChatBot\nHow can I assist you?",
  "I'm just a bot, but I'm here to help!",
  "Good morning! How can I be of service?",
  "Good afternoon! How can I assist you today?",
  "Good evening! How can I help you?",
  "Goodbye! Have a great day!",
  "You're welcome!",
  "I'm here to help. What do you need assistance with?",
  "I'm sorry to hear that. Can you provide more details?",
  "Yes, I understand.",
  "No, I'm sorry, I don't understand.",
  "Sure, please provide more information.",
  "Sure, here is the information you requested.",
  "My name is ChatBot.",
  "I am Chatbot",
  "Go to Consult, select your preferred doctor and book your available date",
  "Pink Aid is one stop centre for Breast Cancer Patient",
  "Breast Cancer is treatable, do not worry, book your consultation to understand your body",
  "Oh No!, are you ok? We have forum for you to find support system to go through this cancer",
  "Oh No!, are you ok? We have forum for you to find support system to go through this cancer",
  "We have quiz and wordle game! Play and Win Now to earn badges",

];