// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrLqBP8PLcSP8FZeZIhRQwo-80QiQlJ6s',
    appId: '1:343820163501:web:0caa73fa33c1cf1ed5a924',
    messagingSenderId: '343820163501',
    projectId: 'pinkaid',
    authDomain: 'pinkaid.firebaseapp.com',
    storageBucket: 'pinkaid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvLoED7cwAL4m4_gbfe9Tf9oZWa7qmRYY',
    appId: '1:343820163501:android:450ae7c1572a8eb5d5a924',
    messagingSenderId: '343820163501',
    projectId: 'pinkaid',
    storageBucket: 'pinkaid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfa4PE-maVPWkhyHLIQLMpBAmqTz_yy4o',
    appId: '1:343820163501:ios:89bdf7af2ab1c5b6d5a924',
    messagingSenderId: '343820163501',
    projectId: 'pinkaid',
    storageBucket: 'pinkaid.appspot.com',
    iosBundleId: 'com.example.pinkaid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfa4PE-maVPWkhyHLIQLMpBAmqTz_yy4o',
    appId: '1:343820163501:ios:89bdf7af2ab1c5b6d5a924',
    messagingSenderId: '343820163501',
    projectId: 'pinkaid',
    storageBucket: 'pinkaid.appspot.com',
    iosBundleId: 'com.example.pinkaid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrLqBP8PLcSP8FZeZIhRQwo-80QiQlJ6s',
    appId: '1:343820163501:web:ac5616528b9b46cbd5a924',
    messagingSenderId: '343820163501',
    projectId: 'pinkaid',
    authDomain: 'pinkaid.firebaseapp.com',
    storageBucket: 'pinkaid.appspot.com',
  );
}
